import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Theme from "@/components/ThemeProvider"

export default function Layout({ children }: any) {
  return (
    <html suppressHydrationWarning>
      <body className={`${montserrat.className} antialiased font-medium`}>
        <Theme>{children}</Theme>
      </body>
    </html>
  )
}


