// 'use client';

// +

import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

// +


// import { Providers } from '../components/';

// +

// import { ThemeProvider } from "../components/theme-provider";
import { type ThemeProviderProps } from "next-themes/dist/types";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// +


// bg-lightbg text-black dark:bg-darkprimary1 dark:text-white

// +

// export default function RootLayout({ children }: ThemeProviderProps) {
//   return (
//     <html lang="en" suppressHydrationWarning className='light' style={{ colorScheme: 'light' }}>
//       <body className={`${montserrat.className}`}>
//       <ThemeProvider>
//         {children}
//       </ThemeProvider>
//       </body>
//     </html>
//   );
// }

// +

// bg-lightbg text-black dark:bg-darkbg dark:text-white


import Theme from "@/components/Theme-provider"

export default function Layout({ children }: ThemeProviderProps) {
  return (
    <html suppressHydrationWarning>
      <body>
        <Theme>{children}</Theme>
      </body>
    </html>
  )
}


